model: 'MiniROAD'
data_name: 'THUMOS'
task: 'OAD'
loss: 'NONUNIFORM'
metric: 'F1'
optimizer: 'AdamW'
device: 'cuda'
feature_pretrained: 'ced'
root_path: './data/THUMOS'
rgb_type: 'ced'
flow_type: 'ced'
annotation_type: 'target_perframe'
video_list_path: 'data_info/video_list.json'
output_path: './output'
window_size: 1
batch_size: 256 
test_batch_size: 1 
num_epoch: 5000 
lr: 0.0001 
weight_decay: 0.05
num_workers: 4
dropout: 0.20
num_classes: 11 # including background
embedding_dim: 256
hidden_dim: 256
num_layers: 3
stride: 4